/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Controller | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author zhuyu
 */
public class StartChoosePanel extends javax.swing.JPanel {

    /**
     * Creates new form StartChoosePanel
     */
    public StartChoosePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        managerButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        managerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        managerButton.setText("I am a Manager");

        customerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerButton.setText("I am a Customer");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerButton)
                    .addComponent(managerButton))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(managerButton)
                .addGap(57, 57, 57)
                .addComponent(customerButton)
                .addGap(49, 49, 49)
                .addComponent(exitButton)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    public JButton getCustomerButton() {
        return customerButton;
    }

    public JButton getExitButton() {
        return exitButton;
    }

    public JButton getManagerButton() {
        return managerButton;
    }

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton managerButton;
    // End of variables declaration//GEN-END:variables
}
